import i18n from '../../i18n/i18n'
export const PRICE_AMOUNT_ALLOWED_REGEX = new RegExp('^[\\d]+(\\.[\\d]+)?$')
export const PRICE_CURRENCY_ALLOWED_REGEX = new RegExp('^[a-zA-ZéáűőúöüóíÉÁŰÖÜÓŐÚÍ]+$')

export const ERR_MSG_PRICE_AMOUNT_REQUIRED = i18n.t('errors.ERR_MSG_PRICE_AMOUNT_REQUIRED')
export const ERR_MSG_PRICE_CURRENCY_REQUIRED = i18n.t('errors.ERR_MSG_PRICE_CURRENCY_REQUIRED')
export const ERR_MSG_PRICE_AMOUNT_INVALID_CHARACTER = i18n.t('errors.ERR_MSG_PRICE_AMOUNT_INVALID_CHARACTER')
export const ERR_MSG_PRICE_CURRENCY_INVALID_CHARACTER = i18n.t('errors.ERR_MSG_PRICE_CURRENCY_INVALID_CHARACTER')
