import i18n from '../../i18n/i18n'

export const ERR_MSG_ORDER_HISTORY_ID_REQUIRED = i18n.t('errors.ERR_MSG_ORDER_HISTORY_ID_REQUIRED')
export const ERR_MSG_ORDER_HISTORY_ORDER_ITEMS_REQUIRED = i18n.t('errors.ERR_MSG_ORDER_HISTORY_ORDER_ITEMS_REQUIRED')
export const ERR_MSG_ORDER_HISTORY_TOTAL_COST_REQUIRED = i18n.t('errors.ERR_MSG_ORDER_HISTORY_TOTAL_COST_REQUIRED')
export const ERR_MSG_ORDER_HISTORY_TOTAL_COST_CURRENCY_REQUIRED = i18n.t('errors.ERR_MSG_ORDER_HISTORY_TOTAL_COST_CURRENCY_REQUIRED')
export const ERR_MSG_ORDER_HISTORY_PAYMENT_TYPE_REQUIRED = i18n.t('errors.ERR_MSG_ORDER_HISTORY_PAYMENT_TYPE_REQUIRED')
export const ERR_MSG_ORDER_HISTORY_ITEM_FOOD_ID_REQUIRED = i18n.t('errors.ERR_MSG_ORDER_HISTORY_ITEM_FOOD_ID_REQUIRED')
export const ERR_MSG_ORDER_HISTORY_ITEM_FOOD_NAME_REQUIRED = i18n.t('errors.ERR_MSG_ORDER_HISTORY_ITEM_FOOD_NAME_REQUIRED')
export const ERR_MSG_ORDER_HISTORY_ITEM_QUANTITY_REQUIRED = i18n.t('errors.ERR_MSG_ORDER_HISTORY_ITEM_QUANTITY_REQUIRED')
export const ERR_MSG_ORDER_HISTORY_ITEM_PRICE_REQUIRED = i18n.t('errors.ERR_MSG_ORDER_HISTORY_ITEM_PRICE_REQUIRED')
