import i18n from '../../../i18n/i18n'
export const ALLERGEN_NAME_VALUE_ALLOWED_CHARACTERS = new RegExp('^[a-zA-ZáéíóöőúüűÁÉÍÓÖŐÚÜŰ]+( [a-zA-ZáéíóöőúüűÁÉÍÓÖŐÚÜŰ]+)*$')
export const ALLERGEN_NAME_VALUE_MIN_LENGTH = 2
export const ALLERGEN_NAME_VALUE_MAX_LENGTH = 254

export const ERR_MSG_ALLERGEN_NAME_VALUE_REQUIRED = i18n.t('errors.ERR_MSG_ALLERGEN_NAME_VALUE_REQUIRED')
export const ERR_MSG_ALLERGEN_NAME_VALUE_LENGTH = i18n.t('errors.ERR_MSG_ALLERGEN_NAME_VALUE_LENGTH', { ALLERGEN_NAME_VALUE_MIN_LENGTH, ALLERGEN_NAME_VALUE_MAX_LENGTH })
export const ERR_MSG_ALLERGEN_NAME_INVALID_CHARACTERS = i18n.t('errors.ERR_MSG_ALLERGEN_NAME_INVALID_CHARACTERS')
