import i18n from '../../i18n/i18n'
export const ERR_MSG_CITY_REQUIRED = i18n.t('errors.ERR_MSG_CITY_REQUIRED')
export const ERR_MSG_STREET_NUMBER_REQUIRED = i18n.t('errors.ERR_MSG_STREET_NUMBER_REQUIRED')
export const ERR_MSG_STREET_REQUIRED = i18n.t('errors.ERR_MSG_STREET_REQUIRED')
export const ERR_MSG_ZIP_CODE_REQUIRED = i18n.t('errors.ERR_MSG_ZIP_CODE_REQUIRED')
export const ERR_MSG_SHIPPING_ADDRESS_REQUIRED = i18n.t('errors.ERR_MSG_SHIPPING_ADDRESS_REQUIRED')
export const ERR_MSG_BILLING_ADDRESS_REQUIRED = i18n.t('errors.ERR_MSG_BILLING_ADDRESS_REQUIRED')
