import { isValidPhoneNumber } from 'libphonenumber-js'
import { containsWhitespace, isBlank } from '../CommonUtils'

export const PHONE_NUMBER_VALUE_ALLOWED_REGEX = new RegExp('^\\+?\\d+$')

export const ERR_MSG_PHONE_NUMBER_REQUIRED = 'A telefonszám megadása kötelező!'
export const ERR_MSG_PHONE_NUMBER_VALUE_REQUIRED = 'A telefonszám megadása kötelező, valamint nem állhat csak szóközből!'
export const ERR_MSG_PHONE_NUMBER_VALUE_INVALID_CHARACTERS = 'A telefonszám csak számokat és + karaktert tartalmazhat!'
export const ERR_MSG_PHONE_NUMBER_VALUE_INVALID = 'Érvénytelen telefonszám!'

export const countryLocalization = {
  af: 'Afganisztán',
  al: 'Albánia',
  dz: 'Algéria',
  as: 'Amerikai Szamoa',
  ad: 'Andorra',
  ao: 'Angola',
  ai: 'Anguilla',
  ag: 'Antigua és Barbuda',
  ar: 'Argentína',
  am: 'Örményország',
  aw: 'Aruba',
  au: 'Ausztrália',
  at: 'Ausztria',
  az: 'Azerbajdzsán',
  bs: 'Bahama-szigetek',
  bh: 'Bahrein',
  bd: 'Banglades',
  bb: 'Barbados',
  by: 'Fehéroroszország',
  be: 'Belgium',
  bz: 'Belize',
  bj: 'Benin',
  bm: 'Bermuda',
  bt: 'Bhután',
  bo: 'Bolívia',
  ba: 'Bosznia-Hercegovina',
  bw: 'Botswana',
  br: 'Brazília',
  io: 'Brit Indiai-óceáni Terület',
  vg: 'Brit Virgin-szigetek',
  bn: 'Brunei',
  bg: 'Bulgária',
  bf: 'Burkina Faso',
  bi: 'Burundi',
  kh: 'Kambodzsa',
  cm: 'Kamerun',
  ca: 'Kanada',
  cv: 'Zöld-foki Köztársaság',
  bq: 'Bonaire, Sint Eustatius és Saba',
  ky: 'Kajmán-szigetek',
  cf: 'Közép-afrikai Köztársaság',
  td: 'Csád',
  cl: 'Chile',
  cn: 'Kína',
  cx: 'Karácsony-sziget',
  cc: 'Kókusz-szigetek',
  co: 'Kolumbia',
  km: 'Comore-szigetek',
  cg: 'Kongó (Brazzaville)',
  cd: 'Kongó (Kinshasa)',
  ck: 'Cook-szigetek',
  cr: 'Costa Rica',
  ci: 'Elefántcsontpart',
  hr: 'Horvátország',
  cu: 'Kuba',
  cw: 'Curaçao',
  cy: 'Ciprus',
  cz: 'Csehország',
  dk: 'Dánia',
  dj: 'Dzsibuti',
  dm: 'Dominika',
  do: 'Dominikai Köztársaság',
  ec: 'Ecuador',
  eg: 'Egyiptom',
  sv: 'Salvador',
  gq: 'Egyenlítői-Guinea',
  er: 'Eritrea',
  ee: 'Észtország',
  et: 'Etiópia',
  fk: 'Falkland-szigetek',
  fo: 'Feröer-szigetek',
  fj: 'Fidzsi-szigetek',
  fi: 'Finnország',
  fr: 'Franciaország',
  gf: 'Francia Guyana',
  pf: 'Francia Polinézia',
  ga: 'Gabon',
  gm: 'Gambia',
  ge: 'Grúzia',
  de: 'Németország',
  gh: 'Ghána',
  gi: 'Gibraltár',
  gr: 'Görögország',
  gl: 'Grönland',
  gd: 'Grenada',
  gp: 'Guadeloupe',
  gu: 'Guam',
  gt: 'Guatemala',
  gg: 'Guernsey',
  gn: 'Guinea',
  gw: 'Bissau-Guinea',
  gy: 'Guyana',
  ht: 'Haiti',
  hn: 'Honduras',
  hk: 'Hongkong',
  hu: 'Magyarország',
  is: 'Izland',
  in: 'India',
  id: 'Indonézia',
  ir: 'Irán',
  iq: 'Irak',
  ie: 'Írország',
  im: 'Man-sziget',
  il: 'Izrael',
  it: 'Olaszország',
  jm: 'Jamaica',
  jp: 'Japán',
  je: 'Jersey',
  jo: 'Jordánia',
  kz: 'Kazahsztán',
  ke: 'Kenya',
  ki: 'Kiribati',
  xk: 'Koszovó',
  kw: 'Kuvait',
  kg: 'Kirgizisztán',
  la: 'Laosz',
  lv: 'Lettország',
  lb: 'Libanon',
  ls: 'Lesotho',
  lr: 'Libéria',
  ly: 'Líbia',
  li: 'Liechtenstein',
  lt: 'Litvánia',
  lu: 'Luxemburg',
  mo: 'Makaó',
  mk: 'Észak-Macedónia',
  mg: 'Madagaszkár',
  mw: 'Malawi',
  my: 'Malajzia',
  mv: 'Maldív-szigetek',
  ml: 'Mali',
  mt: 'Málta',
  mh: 'Marshall-szigetek',
  mq: 'Martinique',
  mr: 'Mauritánia',
  mu: 'Mauritius',
  yt: 'Mayotte',
  mx: 'Mexikó',
  fm: 'Mikronézia',
  md: 'Moldova',
  mc: 'Monaco',
  mn: 'Mongólia',
  me: 'Montenegró',
  ms: 'Montserrat',
  ma: 'Marokkó',
  mz: 'Mozambik',
  mm: 'Mianmar',
  na: 'Namíbia',
  nr: 'Nauru',
  np: 'Nepál',
  nl: 'Hollandia',
  nc: 'Új-Kaledónia',
  nz: 'Új-Zéland',
  ni: 'Nicaragua',
  ne: 'Niger',
  ng: 'Nigéria',
  nu: 'Niue',
  nf: 'Norfolk-sziget',
  kp: 'Észak-Korea',
  mp: 'Északi Mariana-szigetek',
  no: 'Norvégia',
  om: 'Omán',
  pk: 'Pakisztán',
  pw: 'Palau',
  ps: 'Palesztina',
  pa: 'Panama',
  pg: 'Pápua Új-Guinea',
  py: 'Paraguay',
  pe: 'Peru',
  ph: 'Fülöp-szigetek',
  pl: 'Lengyelország',
  pt: 'Portugália',
  pr: 'Puerto Rico',
  qa: 'Katar',
  re: 'Réunion',
  ro: 'Románia',
  ru: 'Oroszország',
  rw: 'Ruanda',
  bl: 'Saint Barthélemy',
  sh: 'Szent Ilona',
  kn: 'Saint Kitts és Nevis',
  lc: 'Saint Lucia',
  mf: 'Saint Martin',
  pm: 'Saint Pierre és Miquelon',
  vc: 'Saint Vincent és Grenadine-szigetek',
  ws: 'Szamoa',
  sm: 'San Marino',
  st: 'São Tomé és Príncipe',
  sa: 'Szaúd-Arábia',
  sn: 'Szenegál',
  rs: 'Szerbia',
  sc: 'Seychelle-szigetek',
  sl: 'Sierra Leone',
  sg: 'Szingapúr',
  sx: 'Sint Maarten',
  sk: 'Szlovákia',
  si: 'Szlovénia',
  sb: 'Salamon-szigetek',
  so: 'Szomália',
  za: 'Dél-afrikai Köztársaság',
  kr: 'Dél-Korea',
  ss: 'Dél-Szudán',
  es: 'Spanyolország',
  lk: 'Srí Lanka',
  sd: 'Szudán',
  sr: 'Suriname',
  sj: 'Svalbard és Jan Mayen',
  sz: 'Szváziföld',
  se: 'Svédország',
  ch: 'Svájc',
  sy: 'Szíria',
  tw: 'Tajvan',
  tj: 'Tádzsikisztán',
  tz: 'Tanzánia',
  th: 'Thaiföld',
  tl: 'Kelet-Timor',
  tg: 'Togo',
  tk: 'Tokelau',
  to: 'Tonga',
  tt: 'Trinidad és Tobago',
  tn: 'Tunézia',
  tr: 'Törökország',
  tm: 'Türkmenisztán',
  tc: 'Turks- és Caicos-szigetek',
  tv: 'Tuvalu',
  ug: 'Uganda',
  ua: 'Ukrajna',
  ae: 'Egyesült Arab Emírségek',
  gb: 'Egyesült Királyság',
  us: 'Amerikai Egyesült Államok',
  uy: 'Uruguay',
  uz: 'Üzbegisztán',
  vu: 'Vanuatu',
  va: 'Vatikán',
  ve: 'Venezuela',
  vn: 'Vietnam',
  vi: 'Amerikai Virgin-szigetek',
  wf: 'Wallis és Futuna',
  eh: 'Nyugat-Szahara',
  ye: 'Jemen',
  zm: 'Zambia',
  zw: 'Zimbabwe'
}

export function validatePhoneNumber(phoneNumber: string) {
  phoneNumber[0] === '+' && (phoneNumber = phoneNumber.substring(1))
  // console.log('asdaaaaa: ' + phoneNumber)
  if (isBlank(phoneNumber)) {
    throw new Error(ERR_MSG_PHONE_NUMBER_VALUE_REQUIRED)
  }
  if (containsWhitespace(phoneNumber)) {
    throw new Error(ERR_MSG_PHONE_NUMBER_VALUE_REQUIRED)
  }
  if(!isValidPhoneNumber('+' + phoneNumber)) {
    // console.log('phoneNumber  isValidPhoneNumber')
    throw new Error(ERR_MSG_PHONE_NUMBER_VALUE_INVALID)
  }
}
